In [1]:
import numpy as np
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt

image = cv2.imread("Seven.jpg")
print(image)

[[[ 7  1 18]
  [ 7  1 18]
  [ 4  1 17]
  ..., 
  [ 5  0 16]
  [ 8  1 16]
  [ 8  0 12]]

 [[ 7  1 18]
  [ 7  1 18]
  [ 4  1 17]
  ..., 
  [ 5  0 16]
  [ 8  1 16]
  [ 8  0 12]]

 [[ 7  1 20]
  [ 7  1 20]
  [ 5  1 20]
  ..., 
  [ 5  0 16]
  [ 8  1 16]
  [ 6  0 12]]

 ..., 
 [[ 0  5 14]
  [ 1  6 15]
  [ 2  5 13]
  ..., 
  [ 4  2 22]
  [ 3  2 22]
  [ 0  1 21]]

 [[ 2  8 15]
  [ 1  7 14]
  [ 2  5 13]
  ..., 
  [ 4  2 21]
  [ 2  2 20]
  [ 0  1 19]]

 [[ 2  8 15]
  [ 1  7 14]
  [ 1  5 10]
  ..., 
  [ 3  1 20]
  [ 2  2 20]
  [ 0  1 19]]]
